"""attendance update

Revision ID: 380e3eb5190e
Revises: 06ce018ca72e
Create Date: 2026-05-22 16:16:05.264693

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '380e3eb5190e'
down_revision = '06ce018ca72e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selfie_file', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('verified_file', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('teacher_decision', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('suspicious_reason', sa.String(length=300), nullable=True))
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.drop_column('latitude')
        batch_op.drop_column('face_distance_ok')
        batch_op.drop_column('longitude')
        batch_op.drop_column('campus_verified')
        batch_op.drop_column('face_count')
        batch_op.drop_column('suspicious')
        batch_op.drop_column('submitted')
        batch_op.drop_column('image_file')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_file', mysql.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('submitted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('suspicious', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('face_count', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('campus_verified', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('longitude', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('face_distance_ok', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('latitude', mysql.FLOAT(), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=True)
        batch_op.drop_column('suspicious_reason')
        batch_op.drop_column('teacher_decision')
        batch_op.drop_column('verified_file')
        batch_op.drop_column('selfie_file')

    # ### end Alembic commands ###
