"""schedule update

Revision ID: aa50df56326c
Revises: 8bcfc7237c22
Create Date: 2026-05-25 10:29:40.221471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa50df56326c'
down_revision = '8bcfc7237c22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valid_from', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('valid_until', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('temporary', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.drop_column('temporary')
        batch_op.drop_column('valid_until')
        batch_op.drop_column('valid_from')

    # ### end Alembic commands ###
