"""add expires_at to notification

Revision ID: b85c106557cc
Revises: ad3f15276336
Create Date: 2026-05-17 14:27:29.051398

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b85c106557cc'
down_revision = 'ad3f15276336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('message',
               existing_type=mysql.VARCHAR(length=300),
               type_=sa.Text(),
               nullable=True)
        batch_op.alter_column('receiver_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('day',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('start_time',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('end_time',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('subject',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('room',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('teacher_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('year',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=20),
               nullable=True)
        batch_op.alter_column('branch',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.alter_column('division',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('schedule_ibfk_1'), type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('schedule_ibfk_1'), 'teacher', ['teacher_id'], ['id'])
        batch_op.alter_column('division',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('branch',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('year',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('teacher_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('room',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('subject',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('end_time',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('start_time',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('day',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('updated_by')

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.alter_column('receiver_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('message',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=300),
               nullable=False)
        batch_op.drop_column('expires_at')

    # ### end Alembic commands ###
