"""empty message

Revision ID: c6d0f3b8b05d
Revises: aa50df56326c
Create Date: 2026-05-25 17:49:00.190212

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c6d0f3b8b05d'
down_revision = 'aa50df56326c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confidence', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('suspicious', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('image_file', sa.String(length=200), nullable=True))
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('teacher_decision',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.drop_column('suspicious_reason')
        batch_op.drop_column('verified_file')
        batch_op.drop_column('timestamp')
        batch_op.drop_column('selfie_file')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selfie_file', mysql.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('timestamp', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('verified_file', mysql.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('suspicious_reason', mysql.VARCHAR(length=300), nullable=True))
        batch_op.alter_column('teacher_decision',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.drop_column('image_file')
        batch_op.drop_column('suspicious')
        batch_op.drop_column('confidence')

    # ### end Alembic commands ###
