"""empty message

Revision ID: e5ba95ab2959
Revises: c6d0f3b8b05d
Create Date: 2026-05-27 23:22:23.593481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5ba95ab2959'
down_revision = 'c6d0f3b8b05d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doubt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_seen', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doubt', schema=None) as batch_op:
        batch_op.drop_column('is_seen')

    # ### end Alembic commands ###
